NumpyArrays

In [7]:
import numpy as np

In [9]:
#creating array 
#from a list 
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [15]:
#Multi-dimensional Arices)ray
arr =np.array([[1,2],[3,4],[4,5]])
print(arr)

[[1 2]
 [3 4]
 [4 5]]


In [17]:
#using Built - in functions 
np.arange(0,10,2) #note last number is intervals

array([0, 2, 4, 6, 8])

In [19]:
#using Built - in functions 
np.arange(0,10,3)

array([0, 3, 6, 9])

In [21]:
#Basic Operations on Arrays

#arithmetic operatiions 
arr =np.array([1,2,3])
print(arr+2) # 2 was added to all values 

[3 4 5]


In [29]:
#Mathematical Functions 
#linear Algebra 
arr1= np.array([[1,2],[3,4]])
arr2 = np.array( [[5,6],[3,4]])
print(np.dot(arr1,arr2))

[[11 14]
 [27 34]]


In [33]:
#slicing 
arr=np.array([10,20,30,40,50])
print(arr[1:4])

[20 30 40]


In [39]:
#Multi dimensional 
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
print(arr3[1,2]) #note  1 is row and 2 is column 

6


In [47]:
print (arr3[:,1])

[2 5 8]


In [49]:
#Stacking and splitiing arrays 
#Horizontal Stacking (along columns):
print (np.hstack((arr1, arr2)))

[[1 2 5 6]
 [3 4 3 4]]


In [51]:
#Vertical  Stacking (along columns):
print (np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [3 4]]


In [71]:
#splitting:
arr4 = np.array([1,2,3,4,5,6])
print (np.split(arr4, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [90]:
#Broadcaasting
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) 
arr2 = np.array([1, 2, 3]) 
print(arr1 + arr2)


[[2 4 6]
 [5 7 9]]
